FROM caddy:2.11-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare

FROM caddy:2.11

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

VOLUME [ "/data", "/config", "/etc/caddy", "/srv" ]
EXPOSE 80/tcp 443/tcp 443/udp
